### ISSUE TITLE
Python module jq is difficult to package

### ISSUE THREAD

**Issue by mavit** [moreati/jq-filter#1]
I notice that the Python module `jq` [requires Internet access at build time](https://github.com/mwilliamson/jq.py/issues/19).  This will prevent it from being packaged as-is for, e.g., Fedora or Debian.  This seems likely to be a hurdle to getting the `jq()` filter into upstream Ansible.

**Comment by moreati** [comment]
Python jq 1.x provides wheels on PyPI
