### ISSUE TITLE
Upstream

### ISSUE THREAD

**Issue by gsauthof** [moreati/jq-filter#2]
Have you considered to submit this filter upstream?

I know Ansible includes `json_query` which uses jmespath, but the `jq` syntax makes more sense to me.

**Comment by moreati** [comment]
I proposed it in https://groups.google.com/forum/#!searchin/ansible-devel/jq%7Csort:date/ansible-devel/kYwimDFU2dc/lbHWnNc3GgAJ, reaction was luke warm. The current trend is moving things out of Ansible core into collections. I don't intend to re-propose this for core.
